<?php
$scope = '';
if ($uiPortal==='bank' && in_array($_SESSION['user_type'],array('user','manager'))) {
    $scope = " WHERE collecting_branch_code='".mysql_real_escape_string($_SESSION['branch_code'])."'";
}
$counts = array('total'=>0,'pending'=>0,'ordered'=>0,'dispatched'=>0,'delivered'=>0,'approval'=>0,'reject'=>0);
$result = mysql_query('SELECT LOWER(rqst_status) AS status, COUNT(*) AS quantity FROM aibl_chq_rqst'.$scope.' GROUP BY LOWER(rqst_status)');
if (!$result) { echo '<div class="notice">Requisition totals could not be loaded. Please try again.</div>'; return; }
while ($row=mysql_fetch_assoc($result)) { $counts['total']+=(int)$row['quantity']; $counts[$row['status']]=(int)$row['quantity']; }
$searchOption = $uiPortal==='bank' && $_SESSION['user_type']==='user' ? 'user_search_criteria' : ($uiPortal==='bank' && $_SESSION['user_type']==='manager' ? 'manager_search_criteria' : 'search_criteria');
$primary = $uiPortal==='vendor' ? 'upload_file' : (in_array($_SESSION['user_type'],array('admin','gsd')) ? 'search_criteria' : ($_SESSION['user_type']==='manager'?'chk_approval_manager':'chk_request'));
?>
<section class="overview-banner"><div><span class="banner-tag">YOUR DAILY WORKSPACE</span><h2>Every request.<br>One organised workflow.</h2><p>Track progress, prepare orders and keep your team moving.</p><a class="button button-light" href="index.php?option=<?php echo $primary; ?><?php echo $primary==='search_criteria'?'&amp;task=search_all':''; ?>"><?php echo $uiPortal==='vendor'?'Import requisitions':ui_title($primary); ?> <?php echo ui_icon('arrow'); ?></a></div><div class="workflow-art" aria-hidden="true"><div class="art-sheet"><span class="art-caption">REQUISITION WORKFLOW</span><span class="art-line"></span><span class="art-line short"></span><div class="art-step"><i>1</i>Request received<span>&#10003;</span></div><div class="art-step"><i>2</i>Order prepared<span>&#10003;</span></div><div class="art-step"><i>3</i>Ready for delivery<span>&rarr;</span></div></div><span class="art-orbit"></span></div></section>
<div class="stats-grid"><?php foreach(array('total'=>'Total requisitions','pending'=>'Pending preparation','ordered'=>'Orders in progress','delivered'=>'Delivered') as $status=>$label): ?><a class="stat-card" href="index.php?option=total_request&amp;task=total_request_<?php echo $status==='total'?'admin':$status; ?>"><span class="stat-top"><?php echo $label; ?><span class="stat-icon <?php echo $status; ?>"><?php echo ui_icon($status==='delivered'?'check':'file'); ?></span></span><strong><?php echo number_format($counts[$status]); ?></strong><span class="stat-caption"><?php echo $status==='total'?'Across your workspace':'View requisitions'; ?> <span>&rarr;</span></span></a><?php endforeach; ?></div>
<div class="dashboard-grid"><section class="panel"><div class="panel-heading"><div><h2>Requisition pipeline</h2><p>Current distribution by status</p></div><span class="chip">Live data</span></div><div class="pipeline"><?php foreach(array('approval'=>'Awaiting approval','pending'=>'Pending','ordered'=>'Ordered','dispatched'=>'Dispatched','delivered'=>'Delivered','reject'=>'Rejected') as $status=>$label): $percentage=$counts['total']?100*$counts[$status]/$counts['total']:0; ?><div class="pipeline-row"><span><?php echo $label; ?></span><div class="progress-track"><div class="progress-fill <?php echo $status; ?>" style="width:<?php echo round($percentage,2); ?>%"></div></div><strong><?php echo number_format($counts[$status]); ?></strong></div><?php endforeach; ?></div></section><section class="panel quick-panel"><div class="panel-heading"><div><h2>Quick actions</h2><p>Pick up where you need to</p></div></div><?php $actions=array($primary, $searchOption); if($uiPortal==='vendor')$actions=array('upload_file','psi_print','serial_no','download_bill'); foreach($actions as $action): ?><a class="quick-action" href="index.php?option=<?php echo $action; ?><?php echo strpos($action,'search')!==false?'&amp;task=search_all':''; ?>"><span class="quick-icon"><?php echo ui_icon(strpos($action,'search')!==false?'search':'file'); ?></span><span><?php echo ui_title($action); ?><small>Open workspace</small></span><?php echo ui_icon('arrow'); ?></a><?php endforeach; ?></section></div>
<section class="panel recent-panel"><div class="panel-heading"><div><h2>Recent requisitions</h2><p>The latest requests in your workspace</p></div><a class="text-link" href="index.php?option=<?php echo $searchOption; ?>&amp;task=search_all">View all &rarr;</a></div><div class="table-scroll"><table class="modern-table"><thead><tr><th>Request</th><th>Customer</th><th>Branch</th><th>Leaves</th><th>Status</th><th>Request date</th></tr></thead><tbody><?php
$result=mysql_query('SELECT rqst_id,cus_name,collecting_branch,total_leaf,rqst_status,rqst_date FROM aibl_chq_rqst'.$scope.' ORDER BY rqst_id DESC LIMIT 8');
if($result && mysql_num_rows($result)) { while($row=mysql_fetch_assoc($result)) { $status=strtolower($row['rqst_status']); echo '<tr><td><span class="request-id">#'.(int)$row['rqst_id'].'</span></td><td>'.ui_escape($row['cus_name']).'</td><td>'.ui_escape($row['collecting_branch']).'</td><td>'.(int)$row['total_leaf'].'</td><td><span class="status-badge '.ui_escape($status).'">'.ui_escape(ucfirst($status)).'</span></td><td>'.ui_escape($row['rqst_date']).'</td></tr>'; } } else echo '<tr><td colspan="6" class="empty-state">No requisitions yet. New requests will appear here.</td></tr>';
?></tbody></table></div></section>
